### ISSUE TITLE
AVAudioSession category

### ISSUE THREAD

**Issue by kcandr** [gizmosachin/VolumeBar#1]
When start VolumeBar it stops playing background music from another app at string
`try AVAudioSession.sharedInstance().setActive(true)` 

When I set ambient category before activate session music continues to play and VolumeBar works
`try AVAudioSession.sharedInstance().setCategory(AVAudioSessionCategoryAmbient)`
`try AVAudioSession.sharedInstance().setActive(true)` 

Thank you

**Comment by gizmosachin** [comment]
Hi @kcandr, thanks for noticing this.

I'm reluctant to set the category to `AVAudioSessionCategoryAmbient` in VolumeBar itself because apps that separately call `setCategory` on `AVAudioSession.sharedInstance()` (with a value other than `AVAudioSessionCategoryAmbient`) would be affected.

However, I'll add a note to the README about the background playback issue and how to avoid it. Thanks!

**Comment by asimonv** [comment]
@gizmosachin I added 
```try AVAudioSession.sharedInstance().setCategory(AVAudioSessionCategoryAmbient)``` before ```VolumeBar.sharedInstance.start()``` and the VolumeBar stops working when I try to change the volume while playing background music, only the HUD appears. 

Is this the expected behavior?

**Comment by gizmosachin** [comment]
@asimonv Definitely not - sorry about that! Just pushed a change (https://github.com/gizmosachin/VolumeBar/commit/d21186c3a022d1b1b2feab5544b79e281eb445c5) and tested it with the `AVAudioSessionCategoryAmbient` category and background music. Let me know if that fixes it.

**Comment by asimonv** [comment]
@gizmosachin nice! Works great. 

Thank you!
